### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by siascone** [whilekofman/Cadence#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page

---

# MVP List
- [x] Should have 7 MVPs.
  - [x] 3 of those are User Auth, Heroku, and Production README.
  - [x] The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
  - [x] MVPs are listed in an ordered list
  - [x] Each MVP is broken down into bullet points

---

# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [x] unique
  - [x] indexed
  - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table’s name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State
- [x] State shape is flat!
- [x] State’s keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
  - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [x] Top level slices
    - [x] `entities`
    - [x] `session`
    - [x] `errors` (here or in `ui`)
    - [x] `ui` (if needed)
  - [x] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can’t change
    + like count and a boolean on whether the user likes the post instead of a likes slice

---

# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn’t need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes
- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
  - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by siascone** [comment]
## Notes:
Please see the [Bluebird Wiki](https://github.com/appacademy/bluebird/wiki) for notes reference

### Wiki Home Page
- remove the headings (#s) from the description, live link placeholder and page links
- make the page links bullets. This can be done with a +, - or * preceding the link with a space

### MVP List
Overall good approach. You have one too many features listed and kudos should be separated into comments and likes. Here is what the features should be listed as and a some notes on what to add/change in your bullets
- MVP #3 - Activities
  - create, edit, show and index (index can be used for feed and for user's activity page)
  - add images to activities
- MVP #4 Comments 
- MVP #5 Kudos (likes)
- MVP #6 User Profile (CRUD)
  - houses index of activates 
- Bonus Features: Follows

### Database Schema
- decide on single names for tables and columns
- index anything you plan to use to look up a table entry with (i.e. username, athlete_id, etc.)
- all table names should be lower cased
- keep an eye on syntax, I see some rogue characters like #

### Sample State
- Be sure to add js after the first set of triple backticks so that the page renders in JavaScript
- maintain naming convention across back and front ends. if it's kudos in the database it should be kudos in the redux state, same for users/athletes etc.
- missing comments slice of state 
- missing ui, errors and session slices of state

### Backend Routes
- remove added horizontal rules h1s and h2s will add those in automatically
- your API Endpoints heading should be the same as the HTML heading
  - I recommend h2s for HTML and API Endpoints and h3s for your subheadings under API Endpoints:
  - In markdown: #=h1, ##=h2,  ###=h3, etc. 
- missing users heading for user routes
- pick naming convention for props/kudos to match across app
- Follow should be Follows


### Frontend Routes
- assuming that the props index is a list of comments/kudos for an activity  `commentIndex` can be rendered on the `activityItem`  iteslf similar to how indexItems are rendered in indexes.
- reccomend not naming a component Props as it may cause reading/talking confusion given that props also means properties of react components. (kudos is good)
- Otherwise looks good

**Comment by siascone** [comment]
## Notes

### Wiki Home page 
- Looks Good
- Your page links, description sentence and live link placeholder don't need to be headings, you can remove the #'s from them if you like.

### MVP List
- Looks good

### Database Schema
- a few of your notes still reference kudos as different names. Pick one.
- otherwise looks good

### Sample State
- looks good

### Backend Routes
- looks good

### Frontend Routes
- Use lowerCamelCase for all wildcards
- Otherwise looks good


Notes on Kudos, in the backend you call them Props and in the frontend you call them Kudos. Make sure this doesn't lead to confusion. I recommend picking one name.

Overall looks good. Consider the notes above and you should be good to start working on your project!

**Comment by whilekofman** [comment]
complete
